Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web01" do |web01|
    web01.vm.box = "generic/ubuntu2004"
    web01.vm.network "private_network", ip: "192.168.56.17"
    web01.vm.network "public_network"
    
    web01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
   end
   
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y apache2 git php-mbstring php-mysql php-xml php-curl php-json php-zip
     curl -sS https://getcomposer.org/installer | php
     sudo mv composer.phar /usr/local/bin/composer
     chmod +x /usr/local/bin/composer
     git clone https://github.com/csinghdev/laravel-starter.git
     cd laravel-starter
     composer install
     cp .env.example .env
   SHELL
  
  end

  # config.vm.define "db01" do |db01|
  #   db01.vm.box = "geerlingguy/centos7"
  #   db01.vm.network "private_network", ip: "192.168.56.18"
  #   db01.vm.network "public_network"
    
  #   db01.vm.provider "virtualbox" do |vb|
  #    vb.memory = "1024"
  #    vb.cpus = 2
  #  end
   
   
  #  config.vm.provision "shell", inline: <<-SHELL
  #    apt-get update
  #    apt-get install -y apache2
  #  SHELL 
  # end
  
  
  
#END OF LINE
end
